config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "admin", password: "5598"

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страничка про нас!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "5598", except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if (@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindToMind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="pt-5">

  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <h5 class="navbar-brand">УмуРазуму</h5>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <span class="p-2 text-dark"><%= link_to "Главная страница", home_path %></span>
          </li>
          <li class="nav-item">
            <span class="p-2 text-dark"><%= link_to "Про нас", about_path %></span>
          </li>
          <li class="nav-item">
            <span class="p-2 text-dark"><%= link_to "Добавить статью", new_post_path %></span>
          </li>
        </ul>

      <nav class="my-2 my-md-0 mr-md-3">
        <span class="btn btn-outline-primary"><%= link_to "Зарегистрироваться" %></span>
        <span class="btn btn-outline-primary"><%= link_to "Войти" %></span>
      </nav>
    </nav>
  </header>







    <div class="container mt-5 pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Наши Услуги</h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"},
            :class => 'btn btn-danger' %>
<hr>
<h2>Отзывы</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
  </div>
<% end %>
<hr>
<h2>Добавить Отзыв</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Имя пользователя<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Текст<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Добавить", {:class => 'btn btn-warning'}) %>
  </p>
<% end %>